name: 'NX Code Coverage'
description: 'Github action for combining/compiling code coverage from an nx monorepo'
author: 'dkhunt27'
branding:
  icon: box
  color: blue
inputs:
  github-token: 
    required: true
    description: Github token
  no-coverage-ran: 
    required: true
    description: true/false if no coverage was ran; useful if using nx affected and it returned no projects
    type: boolean
  coverage-folder: 
    required: false
    description: path to folder containing project folders with coverage data (default 'coverage')
  coverage-base-folder: 
    required: false
    description: path to folder containing project folders with coverage data for diff/base comparison (default 'coverage-base')
  gist-processing:
    required: true
    description: true/false should save results/badge to gist
    type: boolean
  gist-token:
    required: false
    description: 'Your secret with the gist scope for coverage badge; required if gist-processing not false'
  gist-id:
    required: false
    description: 'The ID of the gist to use; required if gist-processing not false'
  label-color:
    description: 'The left color of the badge'
    required: false
  color:
    description: 'The right color of the badge'
    required: false
  is-error:
    description: 'The color will be red and cannot be overridden'
    required: false
  named-logo:
    description: 'A logo name from simpleicons.org'
    required: false
  logo-svg:
    description: 'An svg-string to be used as logo'
    required: false
  logo-color:
    description: 'The color for the logo'
    required: false
  logo-width:
    description: 'The space allocated for the logo'
    required: false
  logo-position:
    description: 'The position of the logo'
    required: false
  style:
    description: 'The style like "flat" or "social"'
    required: false
  cache-seconds:
    description: 'The cache lifetime in seconds (must be greater than 300)'
    required: false
  comment-format:
    description: 'The format of the github comment "verbose" or "concise"'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
